name: flutter_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
          style: italic